/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Entreprise;
import bean.Utilisateur;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import service.CompteTransactionService;
import service.EntrepriseServices;
import util.Session;

/**
 *
 * @author ushiho
 */
public class ConfirmationAjoute extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    EntrepriseServices entrepriseServices = new EntrepriseServices();
    AjouterEntreprise ajouterEntreprise = (AjouterEntreprise) Session.getAttribut("AjouterEntreprise");
    GestionDesEntreprises gestionDesEntreprises = (GestionDesEntreprises) Session.getAttribut("GestionDesEntreprises");
    CompteTransactionService compteTransactionService = new CompteTransactionService();
    short nbEssay = 1;

    public ConfirmationAjoute() {
        initComponents();
    }

    private boolean testPassword() {
        nbEssay++;
        String password = jPasswordField1.getText();
        Utilisateur utilisateur = (Utilisateur) Session.getAttribut("utilisateur");
        return utilisateur.getPassword().equals(password);
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(614, 206));

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        jLabel1.setText("Authentification est obligatoire pour excuté cette opération");

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 6, 6));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(624, 236));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (nbEssay < 3) {

            if (testPassword()) {
                System.out.println(Session.getAttribut("entrepriseSelected"));
                Entreprise nvEntreprise = (Entreprise) Session.getAttribut("entreprise");
                Entreprise ancienEntreprise = (Entreprise) Session.getAttribut("entrepriseSelected");
                if (gestionDesEntreprises.choix == 1) {

                    int res = entrepriseServices.add(nvEntreprise.getNumSecuriteSiege(), nvEntreprise.getTel(), nvEntreprise.getCinChef(),
                            nvEntreprise.getEmail(), nvEntreprise.getAdresse());
                    if (res == 1) {
                        gestionDesEntreprises.entrepriseHelper.setList(entrepriseServices.findAll());
                        JOptionPane.showMessageDialog(null, "L'enregistrement est validé", "Resultat", JOptionPane.INFORMATION_MESSAGE);
                        ajouterEntreprise.hide();
                        ajouterEntreprise.initParam("", "", "", "", "", "Ajouter");
                        this.hide();
                        return;
                    } else if (res < 0) {
                        JOptionPane.showMessageDialog(null, "Cette N.M.S existe déja pour une autre entreprise !", "Erreur", JOptionPane.ERROR_MESSAGE);
                        this.hide();
                        return;
                    }
                }
                if (gestionDesEntreprises.choix == 2) {

                    int res = entrepriseServices.modify(ancienEntreprise.getId(), nvEntreprise);
                    System.out.println(res);
                    if (res == 2) {
                        gestionDesEntreprises.entrepriseHelper.setList(entrepriseServices.findAll());
                        JOptionPane.showMessageDialog(null, "La modification est enregistrée ", "Resultat", JOptionPane.INFORMATION_MESSAGE);
                        ajouterEntreprise.hide();
                        ajouterEntreprise.initParam("", "", "", "", "", "Ajouter");
                        gestionDesEntreprises.getjTextField1().setText("");
                        this.hide();
                        return;
                    }
                    if (res < 0) {
                        JOptionPane.showMessageDialog(null, "cet N.M.S déja existe ,saisir un nouveau N.M.S", "Erreur", JOptionPane.WARNING_MESSAGE);
                        this.hide();
                        return;
                    }
                }
                if (gestionDesEntreprises.choix == 3) {
                    int rep = JOptionPane.showConfirmDialog(null, "Attention ,tout les transactions de cette entreprise vont supprimer", "alert", JOptionPane.WARNING_MESSAGE);
                    if (rep == 0) {
                        int res = entrepriseServices.delete(ancienEntreprise.getId());
                        if (res == 3) {
                            gestionDesEntreprises.entrepriseHelper.remove(ancienEntreprise);
                            JOptionPane.showMessageDialog(null, "La suppression est validée !", "Resultat", JOptionPane.INFORMATION_MESSAGE);
                            this.hide();
                            gestionDesEntreprises.setjTextField1("");
                        } else if (res < 0) {
                            JOptionPane.showMessageDialog(null, "La suppression est erronée ", "Erreur", JOptionPane.ERROR_MESSAGE);
                            this.hide();
                        }
                    } else {
                        this.hide();
                    }
                }

            } else {
                this.jLabel2.setText("votre authentification est erroné ,Réssayer de nouveau!");
                this.jPasswordField1.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Mot de passe incorrect !", "Erreur", JOptionPane.ERROR_MESSAGE);
            this.hide();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationAjoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationAjoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationAjoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationAjoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationAjoute().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
